config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :todos

  get '/' => 'todos#index'
  get 'select/index'
  get 'select/transferto'
  get 'temp/index'
  post 'select/transfertask'
  post 'select/assigntask'

get 'select/listemployee'
get 'select/listmanager'
  post 'select/done'
  post 'select/tasks'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :todos
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  #  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

   protected

   def configure_permitted_parameters
      added_attrs = [:email, :password, :password_confirmation, :remember_me, :fullname]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
 end

end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base

  private

    def post_params
      params.require(:post).permit(:content, :tittle)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:fullname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:fullname, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/select_controller.rb
class SelectController < ApplicationController
  before_filter :authenticate_user!



      def index       #getmethod
      if current_user.ismanager == true
      @users = User.all.order("fullname ASC")
      end
    end

    def listemployee
      if current_user.isemployee
    @users =User.all.order("fullname ASC ")
  end
    if current_user.ismanager
      @users =User.where(managername: current_user.fullname).order("fullname ASC ")
    end
  end

    def listmanager
    @users =User.all.order("fullname ASC ")
    end


def transfertask   #postmethod
    fullname = params[:transfertofullname]
    todoid =params[:todo]
    todo=Todo.where(id: todoid).first
    todo.transferredto=fullname
    todo.transferredby=current_user.fullname
    newuser= User.where(fullname: fullname).first
    newtodo=Todo.new
    newtodo.content=todo.content
    newtodo.transferredto=fullname
    newtodo.transferredby=current_user.fullname
    if !newuser
      return redirect_to '/todos'

    else
    newtodo.user_id=newuser.id
    newtodo.save
    todo.save
  end
    return redirect_to '/todos'

end

  def assigntask   #postmethod
      fullname = params[:assigntofullname]
      todoid =params[:todo]
      todo=Todo.where(id: todoid).first
      deadline=todo.deadline
      todo.assignedto=fullname
      todo.assignedby=current_user.fullname
      newuser= User.where(fullname: fullname).first
      newtodo=Todo.new
      newtodo.content=todo.content
      newtodo.assignedto=fullname
      newtodo.assignedby=current_user.fullname
      newtodo.deadline=todo.deadline
      if !newuser
        return redirect_to '/todos'

      else
      newtodo.user_id=newuser.id

      newtodo.save
      todo.save
    end
      return redirect_to '/todos'

    end


# def transfertask   #postmethod
#
#   email = params[:assigntoemail]
#   todoid =params[:todo]
#
#   todo=Todo.where(id: todoid).first
#
#   # user= todo.user
#                              # puts user.email
#                              # puts todo.transferredto.class
#   todo.assignedto=email
#   todo.save
#   # puts todo.transferredto
#
#                              # puts user.email
#   return redirect_to '/todos'
#                              # @users = User.where(ismanager: true)
#                              # puts @users
# end


	def done     #postmethod
		email = params[:email]
		puts email
		user = User.where(email: email).first

			user.isemployee =!user.isemployee
      if user.isemployee
      user.managername=current_user.fullname
    else
      user.managername=""
    end
      puts user.managername
			user.save
			puts user.isemployee
		return redirect_to '/select/index'
	end

end

app/controllers/temp_controller.rb
class TempController < ApplicationController
  def index
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /todos
  # GET /todos.json
  def index
    if current_user.isemployee==true || current_user.ismanager==true
    @todos = Todo.where(user_id: current_user).order("deadline ASC")
  else
    render "_a"
  end
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = current_user.todos.build
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = current_user.todos.build(todo_params)
    

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:content, :title, :user_id,:deadline)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/select_helper.rb
module SelectHelper
end

app/helpers/temp_helper.rb
module TempHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_user_header.html.erb
<ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
  <script type="text/javascript">
  function myFunction(){
  var pos = window.scrollY;
  var id = setInterval(frame, 1);
  function frame() {
    if (pos <= 0) {
       clearInterval(id);
   } else {
       pos-=10;
         window.scrollTo(0, pos);
   }
  }
  }
  </script>
  <style>

  ul {
      position: fixed;
      width: 100%;
      top:0;
      font-size: 22px;
      list-style-type: none;
      margin: 0;
      padding: 0;
      height: 60px;
      overflow: hidden;
      background-color: #222;
      border-bottom: 1px solid grey;
  }

  li {
      float: right;
  }

  li a {
      display: block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
  }

  li a:hover {
      background-color: #61dafb;
      color: black;
  }
  .about{
    height: 300px;
    width: 100%;
    background-color: #222;
  }
  .companydiv{
    height: 400px;
    width: 100%;
    background-image: url("https://www.threadsol.com/assets/logo-4ffa8e6997c5baf97607f0d254c954b3.png");
     background-repeat: no-repeat;
      background-position: bottom;
      background-attachment: fixed;
  }
  </style>
  <ul>
    <li style="padding-left:40px;letter-spacing: 3px;float:left"><%= link_to 'FullStack', todos_path %></li>

    <li><%= link_to('   Logout', destroy_user_session_path, method: :delete  )%></li>
    <li style="margin-right:40%;letter-spacing: 1px;float:right;color:white;padding-top:15px;">Hello! <%= current_user.try(:fullname) %></li>

  </li>
  </ul>



<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :tittle %><br>
    <%= f.text_field :tittle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.tittle %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Tittle:</strong>
  <%= @post.tittle %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/select/index.html.erb
<!-- <br><br><br><%= link_to 'GoBack', todos_path ,{:style=>'color:black;font-size:25px;padding-top:5px;margin-left:50px;', :class => "css_class"} %> -->
<br><br><br>
<h3 style="margin-left:160px;">You can select your employees</h3>

<% if @users.nil? %>
<% return "you are not authorized yet.Contact your manager or admin"  %>
<% else %>

<table class="centered highlight bordered">
       <thead>
         <tr>
             <th>Email</th>
             <th>Name</th>
             <th>Manager's Name</th>
             <th>Status</th>
         </tr>
       </thead>

       <tbody>
         <% @users.each do |user| %>
         <% value=""%>
         <% if user.isemployee==true%>
         <% value="Not available"%>
         <% else %>
         <% value="Available"%>
         <% end %>
         <% if user.ismanager %>
         <% else %>
         <tr>
           <td><%= user.email %></td>
           <td><%= user.try(:fullname) %></td>
           <td><%= user.try(:managername) %></td>
            <td><form action="/select/done" method="POST">
         <input type="hidden" name="email"  value="<%= user.email %>">
         <a class="btn waves-effect waves-red"><input type="submit" name="makeemployee"value="<%= value%>"></a>
       </form></td>
         </tr>
         <% end %>

         <% end %>

         <% end %>
       </tbody>
     </table>

app/views/select/listemployee.html.erb
<br><br><br>
<!-- <%= link_to 'GoBack', todos_path ,{:style=>'color:black;font-size:25px;padding-top:5px;margin-left:50px;', :class => "css_class"} %> -->

<br>

<p></p>

<h3 style="margin-left:250px;">Listing Employees</h3>

<table class="centered highlight bordered">
       <thead>
         <tr>
             <th>Email</th>
             <th>Name</th>
             <th>Manager's Name</th>
         </tr>
       </thead>

       <tbody>
         <% @users.each do |user| %>
         <% if @users.nil? %>
         <% return "There is no result to show."  %>
         <% else %>
         <% if user.ismanager==true%>
         <% else %>
         <tr>
           <td><%= user.email %></td>
           <td><%= user.try(:fullname) %></td>
           <td><%= current_user.try(:fullname) %></td>
         </tr>
         <% end %>

         <% end %>

         <% end %>
       </tbody>
     </table>

app/views/select/listmanager.html.erb
<br><br><br>
<!-- <%= link_to 'GoBack', todos_path ,{:style=>'color:black;font-size:25px;padding-top:5px;margin-left:50px;', :class => "css_class"} %> -->

<h3 style="margin-left:160px;">Listing Managers</h3>



<table class="centered highlight bordered">
       <thead>
         <tr>
           <th>Manager's Id</th>
             <th>Name</th>
             <th>Email</th>

         </tr>
       </thead>

       <tbody>
         <% @users.each do |user| %>
         <% if @users.nil? %>
         <% return "There is no result to show."  %>
         <% else %>
         <% if user.ismanager==true%>
         <tr>
           <td><%= user.id %></td>
           <td><%= user.try(:fullname) %></td>
           <td><%= user.try(:email) %></td>
         </tr>
         <% else %>

         <% end %>

         <% end %>

         <% end %>
       </tbody>
     </table>

app/views/select/transferto.html.erb
<h1>Hi</h1>


<% @users.try(:each) do |user| %>
<%= user.email %>
<form action="/select/transferred" method="POST">
<input type="hidden" name="email" value="<%= user.email %>"><input type="submit" name="transfertasktomanager"value="<%= user.isemployee%>">
</form>

<% end %>

app/views/temp/index.html.erb
<h1>Temp#index</h1>
<p>Find me in app/views/temp/index.html.erb</p>
<%= link_to('Logout', destroy_user_session_path, method: :delete) %> 

app/views/todos/_a.html.erb
<br><br><br><br><br>


Please contact your manager or admin to get access to this Page.
Thank you
<%= link_to('Logout', destroy_user_session_path, method: :delete) %>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="todoForm">
  <div class="textarea">
    <%= f.label :Content %><br>
    <%= f.text_area :content %>
  </div>

  <div style="" id="divyansh">
    <%= f.label :Deadline %><br>
    <%= f.datetime_select :deadline ,:ampm => true%>


  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>
<script>

</script>

app/views/todos/edit.html.erb
<br><br>
<h4>Editing Todo</h4>
<br><br>
<!-- <%= link_to 'GoBack', todos_path ,{:style=>'color:black;font-size:25px;padding-top:5px;margin-left:50px;', :class => "css_class"} %> -->

<%= render 'form' %>

app/views/todos/index.html.erb
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<style>

@import url('https://fonts.googleapis.com/css?family=Dosis');

tul {
  font-family: 'Dosis', sans-serif;
  list-style-type: none;
    margin: 0;
    padding: 0;
    width: 20%;
    background-color: #333;
    position: fixed;
    top:60px;
    height: 100%;
    overflow: auto;

}
tli {
  margin-bottom: 0px;
}
tli a {
  font-size: 20px;
    display: block;
    color: white;
    padding-left: 50px;
    margin-bottom: 0px;
    text-decoration: none;
    border-bottom: 1px solid grey;
}

/* Change the link color on hover */
tli a:hover {
    background-color: #555;
    color: white;
}
b {
  color: #61dafb;
}
/* Change the link color on hover */
button.accordion {
    background-color: #eee;
    color: #444;
    cursor: pointer;
    padding: 10px;

    border: none;
    text-align: center;
    outline: none;
    font-size: 20px;
    transition: 0.4s;
}





div.panel {
  margin-top: 10px;
  border-radius: 5px;
    padding: 0 18px;
    background-color: #081616;;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.2s ease-out;
}


</style>


<% if current_user.ismanager==false && current_user.isemployee==false%>
<button class="button button3"><%= link_to('   Logout', destroy_user_session_path, method: :delete  )%></button><br>
<% end %>

  <!-- <a href="#home">Home</a>
  <li><a href="#news">News</a></li>
  <li><a href="#contact">Contact</a></li>
  <li><a href="#about">About</a></li> -->
<tul>
<% if current_user.ismanager==true %>
 <tli><%= link_to 'Add Your Employees', select_index_path %></tli><br>
<% end %>
<tli><%= link_to 'List of Employees', select_listemployee_path %></tli><br>

<% if current_user.ismanager==true %>
<tli><%= link_to 'List of Managers', select_listmanager_path %></tli><br>

<% end %>
<tli><%= link_to 'New Todo', new_todo_path %></tli>
</tul>



    <% @todos.each do |todo| %>
    <div class="todos">
                <b>Content: </b> <td><%= todo.content %><br>
              <b>  Deadline : </b><td><%= todo.deadline.strftime("%a, %d %b %Y at %I:%M%p") %><br>
                <button class="accordion">More Options</button>
                    <div class="panel">
          <b>  TransferredTo :</b> <td><%= todo.transferredto %><br>
                <b>    TransferredBy :</b> <td><%= todo.transferredby%><br>
                  <b>    AssignedTo :     </b><%= todo.assignedto %><br>
                    <b>  AssignedBy : </b><%= todo.assignedby%><br>

              <form action="/select/transfertask" method="POST">
                <input type="text" placeholder="Enter fullname"name="transfertofullname">
                <input type="hidden" name="todo" value="<%= todo.id %>">
              <a class="waves-effect waves-light btn">  <input type="submit" name="transfer" value="Transfer"></a>
                </form>

              <form action="/select/assigntask" method="POST">
            <input type="text" placeholder="Enter fullname" name="assigntofullname">
            <input type="hidden" name="todo" value="<%= todo.id %>">
              <a class="waves-effect waves-light btn">  <input type="submit" name="assign" value="Assign"></a>
            </form>

          <i class="material-icons">mode_edit  </i><td><%= link_to 'Edit', edit_todo_path(todo) ,{:style=>'color:#FFFFFF;font-size:30px;padding-top:5px;text-decoration: none;margin-right:75%;', :class => "css_class"}%></td>
          <button class="button button3">  <td><i class="material-icons">delete  </i><%= link_to 'Delete', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td></button><br>
   </div>
</div>

    <% end %>

    <button onclick="myFunction()" name="button" id="movetotop">^</button>
<!-- <div style="height:300px;width:100%;"></div> -->
<br>

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].onclick = function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight){
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    }
  }
}
</script>

app/views/todos/new.html.erb
<br><br><br><br>
<h4 style="margin-left:50px;">New Todo</h4>

<!-- <%= link_to 'GoBack', todos_path ,{:style=>'color:black;font-size:25px;padding-top:5px;text-decoration: none;margin-left:50px;', :class => "css_class"} %> -->
<%= render 'form' %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>
<br><br>
<p>Task has been Created</p>
<p>
  <strong>Content:</strong>
  <%= @todo.content %>
</p>



<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />

<% end -%>
<br>
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>